#!/bin/bash

if [ -z $1 ]
then
        for filename in ./*.JPG
        do
                mv $filename `basename -s .JPG $filename`.jpg
        done
elif [ $1 == "-h" ]
then
        echo "This is help"
else
        cd $1
        for filename in ./*.JPG
        do
                mv $filename `basename -s .JPG $filename`.jpg
        done
fi